[metadata]
    name = advertisement_ai_analytics
    author = aaditya bhatia
    version = 0.0.1
    author_email = bhatiaaadi@gmail.com
    description = For each of the item in an online inventory management system, this tool is responsible for checking the relevancy of the advertisements given by google. 

[build-system]
    requires = ["setuptools>=46.4.0", "wheel"]
    build-backend = "setuptools.build_meta"

[tool.black]
    line-length = 88

[tool.isort]
    profile = "black"

[tool.flake8]
    max-line-length = 88
    extend-ignore = E203

[options]
    python_requires = >=3.7
    tensorflow == 2.5.1
    matplotlib == 3.2.1
    pandas == 1.0.3
    tqdm == 4.45.0
    Unidecode == 1.0.22
    Keras == 2.3.1
    numpy == 1.18.2
    spacy == 2.2.4
    nltk == 3.6.5
    scikit_learn == 0.22.2.post1

#[options.entry_points]
#console_scripts =
#    my-script = my_package.module:my_function